default:
  SCRAM_ARCH: slc7_amd64_gcc10
  CMSSW: CMSSW_12_4_8
  geometry: DB:Extended
  comEnergy: 13600
  customise:
    - Configuration/DataProcessing/Utils.addMonitoring

default_step:
  LHEGEN:
    eventcontent: RAWSIM,LHE
    datatier: GEN,LHE
    step: LHE,GEN
    runUnscheduled: False
  SIM:
    eventcontent: RAWSIM
    datatier: GEN-SIM
    step: SIM
    runUnscheduled: True
  DIGIPremix:
    eventcontent: PREMIXRAW
    datatier: GEN-SIM-DIGI
    step: DIGI,DATAMIX,L1,DIGI2RAW
    procModifiers: premix_stage2
    datamix: PreMix
  HLT:
    eventcontent: RAWSIM
    datatier: GEN-SIM-RAW
    runUnscheduled: False

Run3_Sep22:
  default:
    GlobalTag: 124X_mcRun3_2022_realistic_v10
    era: Run3
    beamspot: Realistic25ns13p6TeVEarly2022Collision
  DIGIPremix:
    pileup_input: dbs:/Neutrino_E-10_gun/Run3Summer21PrePremix-Winter22_122X_mcRun3_2021_realistic_v9-v1/PREMIX
  HLT:
    #GlobalTag: 124X_mcRun3_2022_realistic_forTSG_menu1p4_v1
    step: HLT:@relval2022
    #customise_commands:
    #  - process.hltParticleFlowClusterHBHE.pfClusterBuilder.maxIterations = 5

